### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Oxim0v** [Azuriom/Theme-Prism#2]
Add IPV6 compatibility in the voting page to avoid the infinite loader

`@if(setting('vote.ipv4-v6-compatibility'))
    @push('scripts')
        <script src="https://ipv6-adapter.com/api/v1/api.js" async defer></script>
    @endpush
@endif`

**Comment by MrMicky-FR** [comment]
This theme is already compatible as it doesn’t override the vote views.
