### ISSUE TITLE
Problème couleurs forum

### ISSUE THREAD

**Issue by Yhugzee** [Azuriom/Theme-Prism#5]
Bonjour, j'ai un problème avec le thème
Lorsque que je vais sur l'espace forum il y a du texte blanc sur un fond blanc donc c'est illisible (voire screenshot)
Est-ce possible de modifier

https://i.imgur.com/omPWfW6.png

**Comment by MrMicky-FR** [comment]
En testant avec la dernière version du forum et du thème il n'y a pas ce problème, quels sont les versions utilisés (version d'Azuriom, du thème et du forum)
![](https://user-images.githubusercontent.com/30863452/178100259-601770c5-09f4-427a-96c2-33af78b98e10.png)

**Comment by Yhugzee** [comment]
Azuriom 0.5.1, Forum 0.1.25 et Prism 0.1.8
