### ISSUE TITLE
Problèmes liens menu

### ISSUE THREAD

**Issue by Yhugzee** [Azuriom/Theme-Prism#6]
Bonjour, j'ai update Azuriom en faisant une installation propre et j'ai remis le thème Prism mais il y a un problème.

Avant lorsque l'on se connecter il y avait une barre en haut avec différentes options et en l'installant sur la dernière version de Azuriom il n'y a plus  aucun option et lorsque je clique sur mon pseudo il ne se passe rien sa rajoute juste # au lien

Screenshot :

Avant :
![chrome_JS2CfSqKaA](https://user-images.githubusercontent.com/53708156/180704724-1f3d214f-48e9-4bec-bc2f-14d57e97b925.png)

Maintenant :
![LUtIP5l6Hd](https://user-images.githubusercontent.com/53708156/180704798-8678af8c-90bd-4edb-9e80-1cbd47c39c7b.png)

**Comment by MrMicky-FR** [comment]
Le "avant" n'est même pas un screen du thème Prism mais d'un autre thème (visiblement le thème [Saturne](https://market.azuriom.com/resources/69))
